name: CI/CD_AWS_S3

on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 코드 체크아웃
        uses: actions/checkout@v3
      - name: AWS IAM 사용자 설정
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{secrets.ACCESS_KEY}}
          aws-secret-access-key: ${{secrets.SECRET_KEY}}
          aws-region: ap-northeast-1
      - name: 리액트 빌드
        run: |
          npm install
          npm run build
      - name: S3 업로드
        run: aws s3 sync build/ s3://eunhabucket2 --acl public-read
        env:
          AWS_ACCESS_KEY_ID: ${{secrets.ACCESS_KEY}}
          AWS_SECRET_ACCESS_KEY: ${{secrets.SECRET_KEY}}

          
